# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.TextField(),
        ),
    ]
